# Generated by Django 4.0.4 on 2022-04-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_order',
            new_name='date_added',
        ),
    ]
