# Generated by Django 4.0.4 on 2022-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_customer_alter_shippingaddres_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nuevo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tendencia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
