# Generated by Django 4.0.4 on 2022-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_false',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
